EMAIL_APP: ${EMAIL_APP_NAME}
EMAIL_APP_PW: ${EMAIL_APP_PASSWORD}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  cloud:
    gcp:
      sql:
        enabled: false
        #database-name: amazdog_newsletter
        #instance-connection-name: generated-mote-405209:europe-west1:amazdog-newsletter-mysql

  sql:
    init:
      mode: always

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        show_sql: true
        format_sql: true

      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED

    open-in-view: false
    hibernate:
      ddl-auto: update

  devtools:
    livereload:
      enabled: false

  config:
    import: optional:file:local.env[.properties]

logging:
  level:
    org.springframework.security: trace
    org.hibernate: info
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

  #server:
  #port: ${PORT}
